version: '3.7'
services:
  mailhog:
    image: blueimp/mailhog
    read_only: true
  test:
    build: .
    command: index.test.js
    read_only: true
    environment:
      - WAIT_FOR_HOSTS=mailhog:1025
      - MAILHOG_HOST=mailhog
    volumes:
      - .:/opt:ro
    depends_on:
      - mailhog
